import { AddFirstFillReferenceData } from '../../csc-administration/add-first-fill/add-first-fill.component';

export const ADD_FIRST_FILL_REFERENCE_DATA: AddFirstFillReferenceData = {
  customerSpecificReferenceData: [
    {
      customerId: '6000AMER',
      dateOfInjuryMaximumAgeInDays: 15,
      nonParticipatingEmployers: [],
      forbiddenStates: []
    },
    {
      customerId: '6000CBRS',
      dateOfInjuryMaximumAgeInDays: 15,
      nonParticipatingEmployers: ['Advance Pierre Foods', 'Yaffe'],
      forbiddenStates: []
    },
    {
      customerId: '6000CSOK',
      dateOfInjuryMaximumAgeInDays: 15,
      nonParticipatingEmployers: [],
      forbiddenStates: []
    },
    {
      customerId: '6000FCCI',
      dateOfInjuryMaximumAgeInDays: 30,
      nonParticipatingEmployers: [],
      forbiddenStates: []
    },
    {
      customerId: '6000JECO',
      dateOfInjuryMaximumAgeInDays: 30,
      nonParticipatingEmployers: [
        'ALICO, Inc',
        'Bay County School Board',
        'City of Lauderdale',
        'City of St Petersburg',
        'Employers Mutual Casualty',
        'Intracoastal Health Systems, Inc.',
        'Managee Memorial Hospital, LP',
        'Nassau County Board of County Commission',
        'Pinellas Suncoast Transit Authority',
        "Variety Children's Hospital (Escalate to AM)",
        'Shands Jacksonville Health Care, Inc',
        'Sarasota County Schools District',
        'City of Deltona',
        'City of Punta Gorda',
        'Gulf County Bocc',
        'Highlands County',
        'South Florida Conservancy',
        'City of Miami Beach',
        'Empire Films, Inc',
        'Freseguro-Florida Pacific',
        'FreSeguro-Blue Hammock',
        'Reiter Affiliated Co.-Sandy Ridge',
        'Woodruff & Sons',
        'Orange County BOCC',
        'Pasco County School Board',
        'Pasco County School Board Coverage B',
        'Triangle Grading & Paving',
        'Prewett Enterprises, Inc.',
        'Iron Woman Construction',
        'FCCI Insurance Company',
        'FCCI-National Trust Insurance Company'
      ],
      forbiddenStates: []
    },
    {
      customerId: '6000LWCC',
      dateOfInjuryMaximumAgeInDays: 15,
      nonParticipatingEmployers: [],
      forbiddenStates: []
    },
    {
      customerId: '6000WEST',
      dateOfInjuryMaximumAgeInDays: 15,
      nonParticipatingEmployers: [
        'SOJ AK',
        'SOJ AR',
        'SOJ CA',
        'SOJ CO',
        'SOJ CT',
        'SOJ DC',
        'SOJ HI',
        'SOJ ID',
        'SOJ KS',
        'SOJ LA',
        'SOJ ME',
        'SOJ MD',
        'SOJ MA',
        'SOJ MS',
        'SOJ MO',
        'SOJ MT',
        'SOJ NV',
        'SOJ NH',
        'SOJ NM',
        'SOJ NY',
        'SOJ ND',
        'SOJ OH',
        'SOJ OK',
        'SOJ OR',
        'SOJ RI',
        'SOJ TX',
        'SOJ UT',
        'SOJ VT',
        'SOJ WA',
        'SOJ WY'
      ],
      forbiddenStates: []
    },
    {
      customerId: 'AIMS',
      dateOfInjuryMaximumAgeInDays: 30,
      nonParticipatingEmployers: [
        'Innovative Risk Management - WC',
        'Kern County',
        'Safety National c/o AIMS - K&N Engineering Inc',
        'DFS New York',
        'MONTEREY COUNTY LOCAL AGENCIES INSURANCE AUTHORITY',
        'City of Huntington Beach',
        'City of Sunnyvale',
        'Brentwood Services Inc.',
        'CBCS-INFO ONLY CLIENT',
        'ICW/Veritas-Info Only Client',
        'Lion Raisins',
        'Owl Rock Products Company',
        'Risk Management State Fund',
        'Safety National - Berkeley Farms-c/o AIMS',
        'Safety National - Cal Livery-c/o AIMS',
        'Safety National - Forte c/o AIMS',
        'Safety National--c/o AIMS',
        'SNCCII',
        'Sunnyvale TriStar',
        'Superior Grocers - Safety National',
        'Tristar- Info Only Client',
        'Zacky & Sons Poultry, LLC'
      ],
      forbiddenStates: []
    },
    {
      customerId: 'AMCALAM',
      dateOfInjuryMaximumAgeInDays: 15,
      nonParticipatingEmployers: [],
      forbiddenStates: []
    },
    {
      customerId: 'AMCSACR',
      dateOfInjuryMaximumAgeInDays: 15,
      nonParticipatingEmployers: [],
      forbiddenStates: []
    },
    {
      customerId: 'MIDWEST',
      dateOfInjuryMaximumAgeInDays: 15,
      nonParticipatingEmployers: [
        'TOWER NATIONAL INS CO',
        'TOWER INS OF NEW YORK'
      ],
      forbiddenStates: []
    },
    {
      customerId: 'TRAVELERS',
      dateOfInjuryMaximumAgeInDays: 15,
      nonParticipatingEmployers: [
        'THE KRYSTAL COMPANY',
        'Sally Beauty/Holdings � All states EXCEPT Oregon',
        'Benteler Automotive',
        'ARCTIC CAT',
        'CF TANK LINES INC',
        'CNF INC',
        'CON METCO',
        'CON-WAY INC',
        'EMERY AIR FREIGHT CORP',
        'EMERY GLOBAL LOGISTICS',
        'EMERY WW',
        'EXP CNW, INC',
        'FREIGHTLINER CORP',
        'MENLO WORLDWIDE LOGISTICS',
        'XPO',
        'PEPBOYS',
        'NIPPONKOA',
        'AKIYAMA TSUKEMONO CALIF., INC.',
        'BUDERIM MACADAMIAS OF HAWAII',
        'CALIFORNIA RICE CENTER, INC.',
        'CHOW KING',
        'DAY - LEE FOODS INC',
        'ENAGIC U.S.A,  INC.',
        'GATTEN SUSHI',
        'GLOBAL DINING INC',
        'GMB NORTH AMERICA, INC',
        'GOLDEN GINGER PRODUCTS, INC.',
        'GYU-DAKU RESTAURANT',
        'HAWAII NANILOA HOTEL',
        'HIGUCHI INTERNATIONAL CORP.',
        'HISAMITSU AMERICA',
        'HONEY BEE FOODS CORP',
        'IDEC CORP.',
        'JOLLIBEE RESTAURANTS',
        'JSL FOODS',
        'KAKUICHI  AMERICAN INC',
        'KIKKOMAN CORPORATION',
        'KOSHIN AMERICA CORP.',
        'MACFARMS, LLC',
        'MAGNELL ASSOCIATES',
        'MAKEUP DESIGNERY',
        'MARUKAI CORP.',
        'MIKI ORCHARD, INC.',
        'MIZKAN AMERICAS INC',
        'MUGEN SEIKI RACING, LTD.',
        'NAKANO FOODS',
        'NEW EGG INC',
        'PACIFIC ECHO, INC.',
        'PEC OF AMERICA CORPORATION',
        'PRIME-LINE PRODUCTS CO',
        'RED RIBBON BAKE SHOP',
        'REINS INTERNATIONAL',
        'RICOH ELECTRONICS INC',
        'SAKURA FINETEK USA, INC',
        'SANYO DENKI AMERICA,INC.',
        'SHIN-ETSU POLYMER AMERICA, INC',
        'SLEEP WELL INC',
        'SUNRISE BRANDS, LLC',
        'SUPER FREC USA, INC.',
        'SUSHI BOY, INC.',
        'SWAN FENCE INC.',
        'TOSHIBA AMERICA BUS. SOLUTIONS',
        'TOSHIBA AMERICA INFO SYSTEMS INC',
        'TRANS CIRCLE, INC.',
        'TSURUMI (AMERICA), INC.',
        'UNITED CHEMI-CON',
        'UNITED FINANCIAL OF JAPAN/SANWA',
        'VIE DE FRANCE YAMAZAKI INC',
        'WARABEYA USA, INC.',
        'YAMAMOTO OF ORIENT, INC.',
        'YONEKYU U.S.A., INC.',
        'YOSHINOYA WEST, INC.',
        'YUSHOKEN GATTEN SUSHI USA INC.',
        'KEYS HOLDING GROUP',
        'MERVYNS',
        'PETSMART',
        'TARGET',
        'UNIVERSAL HEALTH SERVICES',
        'P & H MINING aka JOY GLOBAL',
        'HAWAII HEALTH SYSTEM CORP',
        'HARRIS TEETER',
        'RUDDICK CORPORATION',
        'X NON PAR STATE: HI X',
        'EXPRESS SCRIPTS',
        'MEDICAL MANAGEMENT INTERNATIONAL - OH, WA ONLY',
        'CURASCRIPT',
        'BANFIELD PET HOSPITAL',
        'JARDON & HOWARD TECHNOLOGIES - OH ONLY',
        'ABSOPURE - OH ONLY',
        'AETNA LIFE & CASUALTY COMPANY - OH ONLY',
        'AIR FORCE CENTRAL - OH ONLY',
        'ALLIED-SIGNAL INC. - OH ONLY',
        'COOPER-STANDARD AUTOMOTIVE INC - OH ONLY',
        'CROWN CORK & SEAL - OH ONLY',
        'ELECTRONIC DATA SYSTEMS - OH ONLY',
        'FIRST NATIONAL SUPERMARKETS - OH ONLY',
        'FLOWSERVE - OH ONLY',
        'IMO INDUSTRIES INC - OH ONLY',
        'JARDON & HOWARD TECHNOLOGIES - OH ONLY',
        'JASON INCORPORATED - OH ONLY',
        'KINDRED HEALTHCARE INC - OH ONLY',
        'KNIGHT RIDDER - OH ONLY',
        'LITTLE CAESAR ENTERPRISES - OH ONLY',
        'MAC TOOLS - OH ONLY',
        'METROPOLITAN LIFE INSURANCE CO - OH ONLY',
        'METTLER-TOLEDO INC - OH ONLY',
        'NISOURCE - OH ONLY',
        'NORTEK, INC. - OH ONLY',
        'PHILIPS ELECTRONICS NO AMERICA - OH ONLY',
        'PREMIER MFG SUPPORT SVCS INC - OH ONLY',
        'QUEBECOR WORLD (USA) INC - OH ONLY',
        'ROBERT BOSCH CORPORATION - OH ONLY',
        'ROHM AND HAAS CO - OH ONLY',
        'SCHNEIDER NATIONAL INC - OH ONLY',
        'THE COLUMBIA GAS SYSTEM INC - OH ONLY',
        'THE STANLEY WORKS - OH ONLY',
        "TOYS 'R US INC - OH ONLY",
        'U S BANCORP - OH ONLY',
        'VENCOR INC - OH ONLY',
        'W W GRAINGER INC - OH ONLY',
        'WORLD COLOR (USA) CORP - OH ONLY',
        'SAI#2996L1020 AMERICAN WATERWORKS SERVICE CO - OH',
        'AMERICAN WATERWORKS SERVICE CO - OHIO',
        'AMERICAN WATERWORKS SERVICE CO - OHIO',
        'City of Edina',
        'KRAFT POWER CORPORATION-OH ONLY',
        'The Beacon Journal Publishing Co'
      ],
      forbiddenStates: ['HI']
    },
    {
      customerId: 'TRISTAR',
      dateOfInjuryMaximumAgeInDays: 15,
      nonParticipatingEmployers: [],
      forbiddenStates: []
    }
  ],
  relationships: [],
  states: []
};
