import { ActivityResponse } from '../../claim-view/store/models/activity-tab.models';

export const activityResponse: ActivityResponse = {
  activities: [
    {
      activityType: 'Processed Medication',
      creationDate: '08/10/2018',
      prescriberName: '',
      prescriberId: '',
      itemName: 'ONDANSETRON  TAB 4MG ODT',
      daysSupply: '3',
      quantity: '9',
      pharmacy: 'TRINITY DISCOUNT DRUGS',
      descriptionReason: 'POS Transaction',
      outcome: 'Paid',
      paidAmount: '$123.40',
      modifiedByUser: 'SYSTEM',
      dateModified: '08/29/2018',
      priorAuthDateRange: '2001-01-01 to 2020-01-01',
      productType: 'Pharmacy',
      dateFilled: '08/11/2018',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521',
      isCompound: false
    },
    {
      activityType: 'Processed Medication',
      creationDate: '08/09/2018',
      prescriberName: '',
      prescriberId: '',
      itemName: 'METHOCARBAM  TAB 500MG',
      daysSupply: '3',
      quantity: '9',
      pharmacy: 'TRINITY DISCOUNT DRUGS',
      descriptionReason: 'POS Transaction',
      outcome: 'Paid',
      paidAmount: '$5.27',
      modifiedByUser: 'SYSTEM',
      dateModified: '08/22/2018',
      priorAuthDateRange: '2002-01-01 to 2020-01-01',
      productType: 'Pharmacy',
      dateFilled: '08/12/2018',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521',
      isCompound: false
    },
    {
      activityType: 'EPAQ',
      creationDate: '08/09/2018',
      prescriberName: 'COLLINS, RONALD',
      prescriberId: '12345678',
      itemName: 'ONDANSETRON  TAB 4MG',
      daysSupply: '3',
      quantity: '9',
      pharmacy: 'TRINITY DISCOUNT DRUGS',
      descriptionReason: 'Product/Service Not Covered',
      outcome: 'Approved',
      paidAmount: null,
      modifiedByUser: '',
      dateModified: '',
      priorAuthDateRange: '2001-01-03 to 2020-01-01',
      productType: 'Pharmacy',
      dateFilled: '08/01/2018',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521',
      isCompound: false
    },
    {
      activityType: 'Processed Medication',
      creationDate: '08/02/2018',
      prescriberName: 'ZRAUS, THOMAS J',
      prescriberId: '12345678',
      itemName: 'HYDROCO/APAP TAB 10-325MG',
      daysSupply: '28',
      quantity: '84',
      pharmacy: 'TRINITY DISCOUNT DRUGS',
      descriptionReason: 'POS Transaction',
      outcome: 'Paid',
      paidAmount: '$48.02',
      modifiedByUser: 'SYSTEM',
      dateModified: '08/15/2018',
      priorAuthDateRange: '2006-01-01 to 2020-01-01',
      productType: 'Pharmacy',
      dateFilled: '08/13/2018',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521',
      isCompound: false
    },
    {
      activityType: 'Processed Medication',
      creationDate: '08/02/2018',
      prescriberName: 'COLLINS, RONALD L MD',
      prescriberId: '12345678',
      itemName: 'LYRICA       CAP 100MG',
      daysSupply: '30',
      quantity: '90',
      pharmacy: 'TRINITY DISCOUNT DRUGS',
      descriptionReason: 'POS Transaction',
      outcome: 'Paid',
      paidAmount: '$692.99',
      modifiedByUser: 'SYSTEM',
      dateModified: '08/15/2018',
      priorAuthDateRange: '2001-01-01 to 2020-01-01',
      productType: 'Pharmacy',
      dateFilled: '08/11/2018',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521',
      isCompound: false
    },
    {
      activityType: 'Processed Medication',
      creationDate: '08/02/2018',
      prescriberName: 'COLLINS, RONALD L MD',
      prescriberId: '12345678',
      itemName: 'MELOXICAM    TAB 15MG',
      daysSupply: '30',
      quantity: '30',
      pharmacy: 'TRINITY DISCOUNT DRUGS',
      descriptionReason: 'POS Transaction',
      outcome: 'Paid',
      paidAmount: '$87.04',
      modifiedByUser: 'SYSTEM',
      dateModified: '08/15/2018',
      priorAuthDateRange: '2001-01-06 to 2020-01-01',
      productType: 'Pharmacy',
      dateFilled: '08/21/2018',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521',
      isCompound: false
    },
    {
      activityType: 'Processed Medication',
      creationDate: '08/02/2018',
      prescriberName: 'COLLINS, RONALD L MD',
      prescriberId: '12345678',
      itemName: 'METAXALONE   TAB 800MG',
      daysSupply: '30',
      quantity: '90',
      pharmacy: 'TRINITY DISCOUNT DRUGS',
      descriptionReason: 'POS Transaction',
      outcome: 'Paid',
      paidAmount: '$315.41',
      modifiedByUser: 'SYSTEM',
      dateModified: '08/15/2018',
      priorAuthDateRange: '2005-01-01 to 2020-01-01',
      productType: 'Pharmacy',
      dateFilled: '08/11/2018',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521',
      isCompound: false
    },
    {
      activityType: 'Federal Mandated Recall of Processed Medication',
      creationDate: '08/12/2018',
      prescriberName: 'COLLINS, RONALD L MD',
      prescriberId: '12345678',
      itemName: 'SOMESCARY DRUG   TAB 800MG',
      daysSupply: '30',
      quantity: '90',
      pharmacy: 'NOTREAL',
      descriptionReason: 'POS Transaction',
      outcome: 'Paid',
      paidAmount: '$30,015.41',
      modifiedByUser: 'SYSTEM',
      dateModified: '08/15/2018',
      priorAuthDateRange: '2005-01-01 to 2020-01-01',
      productType: 'Pharmacy',
      dateFilled: '08/11/2018',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521',
      isCompound: false
    },
    {
      activityType: 'Paper Bill Roster',
      creationDate: '01/04/2017',
      dateFilled: '01/09/2017',
      itemName: 'Trazodone Tablet',
      daysSupply: '0',
      pharmacy: 'Target',
      prescriberName: 'Dr. John Jenkins',
      prescriberId: '12345678',
      descriptionReason: 'Had no money',
      outcome: 'Waiting',
      paidAmount: '',
      modifiedByUser: 'LMCNEAL',
      dateModified: '01/09/2017',
      priorAuthDateRange: '',
      productType: 'Pharmacy',
      quantity: '0',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521',
      isCompound: false
    },
    {
      activityType: 'Paper Bill Roster',
      creationDate: '01/04/2017',
      dateFilled: '01/09/2017',
      itemName: 'Trazodone Tablet 50mg',
      daysSupply: '5',
      pharmacy: 'KTN Medical',
      prescriberName: 'Dr. John Jenkins',
      prescriberId: '12345678',
      descriptionReason: 'Had no money',
      outcome: 'Waiting',
      paidAmount: '',
      modifiedByUser: 'LMCNEAL',
      dateModified: '01/09/2017',
      priorAuthDateRange: '',
      productType: 'Clinical',
      quantity: '60',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521',
      isCompound: false
    },
    {
      activityType: 'Paper Bill Roster',
      creationDate: '01/04/2017',
      dateFilled: '01/09/2017',
      itemName: 'DICLOFENAC SOL 1.5%',
      daysSupply: '5',
      pharmacy: 'Target',
      prescriberName: 'Dr. John Jenkins',
      prescriberId: '12345678',
      descriptionReason: 'Had no money',
      outcome: 'Waiting',
      paidAmount: '',
      modifiedByUser: 'LMCNEAL',
      dateModified: '01/09/2017',
      priorAuthDateRange: '',
      productType: 'Clinical',
      quantity: '150',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521',
      isCompound: false
    },
    {
      activityType: 'Paper Bill Roster',
      creationDate: '01/04/2017',
      dateFilled: '01/09/2017',
      itemName: 'NAPROXEN TAB 500MG',
      daysSupply: '5',
      pharmacy: 'Target',
      prescriberName: 'Dr. John Jenkins',
      prescriberId: '12345678',
      descriptionReason: 'Had no money',
      outcome: 'Waiting',
      paidAmount: '',
      modifiedByUser: 'LMCNEAL',
      dateModified: '01/09/2017',
      priorAuthDateRange: '',
      productType: 'Clinical',
      quantity: '60',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521',
      isCompound: false
    },
    {
      activityType: 'POS reject',
      creationDate: '01/10/2017',
      dateFilled: '01/09/2017',
      itemName: 'Lidoderm DIS 5%',
      daysSupply: '0',
      pharmacy: 'CVS',
      prescriberName: 'Dr. John Jenkins',
      prescriberId: '12345678',
      descriptionReason: 'Barked like a seal and insulted the queen',
      outcome: 'Waiting',
      paidAmount: '',
      modifiedByUser: 'LMCNEAL',
      dateModified: '01/09/2017',
      priorAuthDateRange: '',
      productType: 'Clinical',
      quantity: '0',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521',
      isCompound: false
    },
    {
      activityType: 'Mail Order Referral',
      creationDate: '01/02/2017',
      dateFilled: '01/09/2017',
      itemName: 'N/A',
      daysSupply: '0',
      pharmacy: 'Walgreens',
      prescriberName: 'Dr. Jane Doe',
      prescriberId: '12345678',
      descriptionReason: 'WellDyneRx',
      outcome: 'Waiting',
      paidAmount: '',
      modifiedByUser: 'LMCNEAL',
      dateModified: '01/09/2017',
      priorAuthDateRange: '',
      productType: 'Clinical',
      quantity: '0',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521',
      isCompound: false
    },
    {
      activityType: 'Something Ancillary',
      creationDate: '01/02/2017',
      dateFilled: '01/09/2017',
      itemName: 'Wheelchair',
      daysSupply: '0',
      pharmacy: `Bob's discount medical products`,
      prescriberName: 'Dr. Smith',
      prescriberId: '12345678',
      descriptionReason: 'Claimant has no legs',
      outcome: 'Delivered',
      paidAmount: '$134.76',
      modifiedByUser: 'LMCNEAL',
      dateModified: '01/09/2017',
      priorAuthDateRange: '',
      productType: 'Ancillary',
      quantity: '0',
      rush: false,
      serviceType: '',
      requestorRole: 'req. Role',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521',
      isCompound: false
    }
  ],
  serverErrors: ['ePAQ']
};
