import { ActivityResponse } from '@shared/models/claim-activity-data';

export const clinicalHistory: ActivityResponse = {
  activities: [
    {
      activityType: 'Paper Bill Roster',
      creationDate: '01/04/2017',
      dateFilled: '01/09/2017',
      itemName: 'Trazodone Tablet 50mg',
      daysSupply: '5',
      pharmacy: 'KTN Medical',
      prescriberName: 'Dr. John Jenkins',
      prescriberId: '12345678',
      descriptionReason: 'Had no money',
      outcome: 'Waiting',
      paidAmount: '',
      modifiedByUser: 'LMCNEAL',
      dateModified: '01/09/2017',
      priorAuthDateRange: '',
      productType: 'Clinical',
      quantity: '60',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521'
    },
    {
      activityType: 'Paper Bill Roster',
      creationDate: '01/04/2017',
      dateFilled: '01/09/2017',
      itemName: 'DICLOFENAC SOL 1.5%',
      daysSupply: '5',
      pharmacy: 'Target',
      prescriberName: 'Dr. John Jenkins',
      prescriberId: '12345678',
      descriptionReason: 'Had no money',
      outcome: 'Waiting',
      paidAmount: '',
      modifiedByUser: 'LMCNEAL',
      dateModified: '01/09/2017',
      priorAuthDateRange: '',
      productType: 'Clinical',
      quantity: '150',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521'
    },
    {
      activityType: 'Paper Bill Roster',
      creationDate: '01/04/2017',
      dateFilled: '01/09/2017',
      itemName: 'NAPROXEN TAB 500MG',
      daysSupply: '5',
      pharmacy: 'Target',
      prescriberName: 'Dr. John Jenkins',
      prescriberId: '12345678',
      descriptionReason: 'Had no money',
      outcome: 'Waiting',
      paidAmount: '',
      modifiedByUser: 'LMCNEAL',
      dateModified: '01/09/2017',
      priorAuthDateRange: '',
      productType: 'Clinical',
      quantity: '60',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521'
    },
    {
      activityType: 'POS reject',
      creationDate: '01/10/2017',
      dateFilled: '01/09/2017',
      itemName: 'Lidoderm DIS 5%',
      daysSupply: '0',
      pharmacy: 'CVS',
      prescriberName: 'Dr. John Jenkins',
      prescriberId: '12345678',
      descriptionReason: 'Barked like a seal and insulted the queen',
      outcome: 'Waiting',
      paidAmount: '',
      modifiedByUser: 'LMCNEAL',
      dateModified: '01/09/2017',
      priorAuthDateRange: '',
      productType: 'Clinical',
      quantity: '0',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521'
    },
    {
      activityType: 'Mail Order Referral',
      creationDate: '01/02/2017',
      dateFilled: '01/09/2017',
      itemName: 'N/A',
      daysSupply: '0',
      pharmacy: 'Walgreens',
      prescriberName: 'Dr. Jane Doe',
      prescriberId: '12345678',
      descriptionReason: 'WellDyneRx',
      outcome: 'Waiting',
      paidAmount: '',
      modifiedByUser: 'LMCNEAL',
      dateModified: '01/09/2017',
      priorAuthDateRange: '',
      productType: 'Clinical',
      quantity: '0',
      rush: false,
      serviceType: '',
      requestorRole: '',
      requestorName: '',
      vendor: '',
      vertice25Link: 'https://http.cat/200',
      ndc: '',
      nabp: '0105521'
    }
  ],
  serverErrors: []
};
